### ISSUE TITLE
Default bike image link incorrect

### ISSUE THREAD

**Issue by realchrisolin** [bikeindex/bike_index#219] opened 2016-06-15 15:33 UTC
https://bikeindex.org/bikes/80752 displays the following image when shared on social media sites: https://bikebook.s3.amazonaws.com/uploads/Fr/6774/feather-usa2-main-photo-large.jpg

It should be sharing the user uploaded images (https://files.bikeindex.org/uploads/Pu/56763/large_IMG_1143.JPG) instead. I've narrowed this issue down to the <meta property="og:image" content value, which I can see is being set in app/helpers/header_tag_helper.rb, but I don't know enough Ruby to figure out why the content value is being set incorrectly. On the theft report for this bike, you can see that it is pointing to the image on AWS instead of the one uploaded by the user.

https://github.com/bikeindex/bike_index/blob/master/app/helpers/header_tag_helper.rb#L112-143, least I think this is the relevant code block.

My theory is that the user created the theft report, then went back and edited it to include the images they uploaded, which didn't update the og:image value. Waiting to hear back from the user-- nevermind, she just confirmed that's exactly what happened as I was updating this. I'll see if I can figure out a way to get this value to update automatically when new images are uploaded.

In the meantime, is this something we can manually update by hand? I don't know if my developer access gives me the ability to fix stuff like this.

**Comment by AWildColin** [comment] 2016-06-15 15:56
I just did some testing with one of my bikes and the og:image content value auto-updated. I'm trying to get the user to delete the photos she uploaded, then upload them again to see if it updates the URL. Since this shouldn't have happened in the first place, there's probably a bug caused by a specific data condition that causes the og:image content value to not update. Hopefully, it can be easily worked around until we figure out what's causing it.

**Comment by wildcolin** [comment] 2016-06-15 16:09
Confirmed deleting and re-uploading user pictures fixes this issue. Since this is a pretty minor issue that isn't frequently occurring, I'll close this and we can reopen it in the future if necessary.

**Comment by sethherr** [comment] 2016-06-22 08:27
More reporting:

>I'm seeing the issue I reported in https://github.com/bikeindex/bike_index/issues/219 happening again, this time in https://bikeindex.org/bikes/74916. The owner originally filed the theft report without an image, then went back and uploaded one afterwards. It's correctly showing on the theft report page, but the og:image value is pointing to https://bikeindex.org/assets/logos/bw_transparent.png instead of https://files.bikeindex.org/uploads/Pu/57271/large_6608188028237353406.jpg.

>In the original report that encountered this issue, I had thought this issue was resolved by the owner deleting and re-uploading the pictures she had uploaded, but I later found out that she never did this. The meta property updated seemingly on it's own or someone manually updated it. Either way, it's not reliably updating when a new image is uploaded and prompted me to send out this email.

>Strangely enough, I was unable to replicate this when updating images for my existing bikes. The og:image value would update to the location of the first image associated with a registration report, for lack of a better term.

**Comment by sethherr** [comment] 2019-07-10 16:35
I believe this is now fixed!

**Closed by sethherr** 2019-07-10 16:35 UTC
